project_id = "jkrwyotrdlucyynnotpd"

[api]
enabled = true
port = 54321
schemas = ["public", "graphql_public"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[auth]
enabled = true
port = 54324
site_url = "https://jkrwyotrdlucyynnotpd.vercel.app"
additional_redirect_urls = ["https://jkrwyotrdlucyynnotpd.vercel.app/vault-dashboard"]
jwt_expiry = 3600
refresh_token_rotation_enabled = true
security_update_password_require_reauthentication = true
security_captcha_enabled = false
security_captcha_provider = "turnstile"
enable_signup = true
enable_anonymous_sign_ins = false
enable_email_confirmations = false
enable_password_strength = true
password_min_length = 8
enable_leaked_password_protection = true

[functions.shopify-order-paid]
verify_jwt = false

[functions.validate-token]
verify_jwt = false