project_id = "jkrwyotrdlucyynnotpd"

[api]
enabled = true
port = 54321
schemas = ["public", "graphql_public"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[auth]
enabled = true
site_url = "https://vault.crypdawgs.com"
additional_redirect_urls = [
  "https://vault.crypdawgs.com/*",
  "https://vault.crypdawgs.com/auth/callback",
  "https://vault.crypdawgs.com/#/vault",
  "http://localhost:5173/*",
  "http://localhost:5173/#/vault"
]
jwt_expiry = 3600
enable_signup = false
enable_anonymous_sign_ins = false

[functions.shopify-order-paid]
verify_jwt = false

[functions.validate-token]
verify_jwt = false